<!DOCTYPE html>
<html lang="en">
    <head>
    	<meta charset="utf-8" />
        <meta name="description" content="Dao User" />
        <meta name="keywords" content="HTML,CSS,JavaScript,PHP" />
        <meta name="author" content="JYS" />
        <link rel="icon" href="/img/favicon.ico" type="image/x-icon" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />

        <link rel="stylesheet" type="text/css" href="css/styles.css" />
        <?php if (!isset($_SESSION['user_id'])) :?>
            <style type="text/css">
                body {background-color: #f5f5f5;}
            </style>
        <?php endif ?>
        <?php if (isset($title)): ?>
        	<title>App | <?= $title ?></title>
        <?php else: ?>
        	<title>App</title>
        <?php endif ?>
    </head>
    <body>
        <header>
    	    <?php require 'navbar.phtml'; ?>
        </header>
    	<main role="main" class="container p-5">