<nav class="navbar navbar-expand-md navbar-light bg-light border-bottom fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active"><a class="nav-link" href="/">Home</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active mr-3"><a class="nav-link" href="/login">Sign in</a></li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <a href="/register" class="btn btn-primary my-2 my-sm-0">Sign up</a>
            </form>
        </div>
    </div>
</nav>
<?php if ($flashes): ?>
<header>
    <div class="alert alert-info text-center" role="alert">
        <?php foreach ($flashes as $flash) echo $flash; ?>
    </div>
</header>
<?php endif ?>