<nav class="navbar navbar-expand-md navbar-light bg-light border-bottom fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active"><a class="nav-link" href="/">Home</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active mr-3"><a class="nav-link" href="/login">Sign in</a></li>
                <form class="form-inline my-2 my-lg-0">
                    <a href="/register" class="btn btn-primary my-2 my-sm-0">Sign up</a>
                </form>
                <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings </a>
                    <div class="dropdown-menu dropdown-menu-right fs-14" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                    </div>
                </li> -->
            </ul>
        </div>
    </div>
</nav>