<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Apellido</th>
            <th>Nombre</th>
            <th>Email</th>
            <th>Creado</th>
            <th>Modificado</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $key => $user) :?>
            <tr>
                <td><?= $user['lastname'] ?></td>
                <td><?= $user['firstname'] ?></td>
                <td><?= $user['email'] ?></td>
                <td><?= $user['created'] ?></td>
                <td><?= $user['modified'] ?></td>
                <td class="text-center">
                    <a href="/edit?id=<?= $user['user_id'] ?>" class="btn btn-warning btn-sm" title="Edit">Edit</a>&nbsp;
                    <a href="/delete?id=<?= $user['user_id'] ?>" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete to ' + '<?= $user['lastname'] . ' ' . $user['firstname'] ?>?')" title="Delete">Delete</a>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>