<section class="">
	<div class="row">
		<div class="container container--login">
			<!-- <img class="img-fluid mx-auto d-block mb-5" style="width: 65px; height: 65px" src="" alt=""> -->
			<?php /*flash('flash_success'); flash('flash_error');*/ ?>
			<h1 class="mb-1 text-center" style="font-size: 34px">Inicia sesión</h1>
			<p class="fs-14 text-muted text-center mb-5">Complete sus datos para ingresar en la app.</p>
			<form action="/login.php" method="POST">
				<div class="form-group">
					<label for="email">Correo electrónico</label>
					<input autocomplete="off" type="email" name="email" class="form-control form-control-lg" size="20" value="" autofocus>
					<div class="invalid-feedback"></div>
				</div>
				<div class="form-group">
					<label for="password">Contraseña</label>
					<a class="form-sublink" href="">¿Olvidó su contraseña?</a>
					<input type="password" name="password" class="form-control form-control-lg" size="20">
					<div class="invalid-feedback"></div>
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-primary btn-block mb-4">Ingresar</button>
				</div>
			</form>
			<p class="small text-center text-muted">¿Aún no tienes una cuenta? <a href="">Regístrate</a></p>
		</div>
	</div>
</section>