<section style="margin-top: 80px;">
	<h1 class="mb-1 text-center font-weight-normal" style="font-size: 34px">Restablecer contraseña</h1>
	<div style="width: 100%; max-width: 380px; padding: 15px; margin: auto;">
		<!-- <img class="img-fluid mx-auto d-block mb-5" style="width: 65px; height: 65px" src="" alt=""> -->
		<?php /*flash('flash_success'); flash('flash_error');*/ ?>
		<form action="" method="POST">
			<div class="form-group">
				<div id="emailHelpInline" class="text-muted mb-1 fs-14">Introduzca su dirección de correo electrónico y le enviaremos un enlace para restablecer su contraseña.</div>
				<input autocomplete="off" type="email" name="email" class="form-control" size="20" value="" autofocus aria-describedby="emailHelpInline">
				<div class="invalid-feedback"></div>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary btn-lg btn-block mb-4">Enviar correo electrónico</button>
			</div>
		</form>
	</div>
</section>