<section class="" style="margin-top: 80px;">
	<div style="width: 100%; max-width: 420px; padding: 15px; margin: auto;" class="bg-white p-4 rounded">
	<h1 class="mb-1 text-center font-weight-normal" style="font-size: 34px">Restablecer contraseña</h1>
		<!-- <img class="img-fluid mx-auto d-block mb-5" style="width: 65px; height: 65px" src="" alt=""> -->
		<form action="/password_reset" method="POST">
			<div class="form-group">
				<div id="emailHelpInline" class="text-muted mb-1">Introduzca su dirección de correo electrónico y le enviaremos un enlace para restablecer su contraseña.</div>
				<input autocomplete="off" type="email" name="email" class="form-control" size="20" value="" autofocus aria-describedby="emailHelpInline">
				<div class="invalid-feedback"></div>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary btn-lg btn-block mb-4">Enviar correo electrónico</button>
			</div>
		</form>
	</div>
</section>