<section class="">
	<div style="width: 100%; max-width: 420px; padding: 15px; margin: auto;">
		<div class="text-center">
			<h1 class="mb-1 font-weight-normal" style="font-size: 34px">Regístrese</h1>
			<p class="fs-14 text-muted mb-5">Ingresa tus datos para crear tu cuenta de acceso.</p>
		</div>
		<form action="/register" method="POST">
			<div class="form-group">
				<label for="email">Tu correo electrónico <span class="required">*</span></label>
				<input type="email" name="email" id="email" class="form-control" autofocus placeholder="ejemplo@email.com" value="" size="30">
				<div class="invalid-feedback"></div>
			</div>
			<div class="form-row">
				<div class="col-md-6 mb-3">
					<label for="firstname">Nombre <span class="required">*</span></label>
					<input type="text" name="firstname" id="firstname" class="form-control" value="" size="20">
					<div class="invalid-feedback"></div>
				</div>
				<div class="col-md-6 mb-3">
					<label for="lastname">Apellido <span class="required">*</span></label>
					<input type="text" name="lastname" id="lastname" class="form-control" value="" size="20">
					<div class="invalid-feedback"></div>
				</div>
			</div>
			<div class="form-group mb-4">
				<label for="password" class="d-block">Crea una contraseña <span class="required">*</span></label>
				<div id="passwordHelpInline" class="text-muted mb-1 fs-14">Las contraseñas deben tener por lo menos 8 caracteres y tener una combinación de letras, números y otros caracteres.</div>
				<input type="password" name="password" id="password" class="form-control" aria-describedby="passwordHelpInline" size="20">
				<div class="invalid-feedback"></div>
			</div>
			<div class="row">
				<div class="col-6">
					<a href="/" class="">Atrás</a>
				</div>
				<div class="col-6">
					<button type="submit" class="btn btn-lg btn-primary float-right">Regístrate</button>
				</div>
			</div>
		</form>
	</div>
</section>